name: Export Secrets to Artifact

on:
  workflow_dispatch:

env:
  PREFIX_SECRETS: 'SECRETS_'

jobs:
    export-secrets-org:
      name: Export Secrets (org)
      runs-on: windows-latest
      steps:
        - name: Export Secrets to CSV (org)
          uses: martins-vds/export-secrets-action@v1.2
          env:
            SECRETS_ORG_SECRET1: ${{ secrets.ORG_SECRET1 }}
            SECRETS_ORG_SECRET2: ${{ secrets.ORG_SECRET2 }}
          with:
            repository: ${{ github.repository }}
            secrets-prefix: 'SECRETS_'
            secrets-type: 'org'
    export-secrets-repo:
      name: Export Secrets (repo)
      runs-on: windows-latest
      steps:
        - name: Export Secrets to CSV (repo)
          uses: martins-vds/export-secrets-action@v1.2
          env:
            SECRETS_REPO_SECRET1: ${{ secrets.REPO_SECRET1 }}
            SECRETS_REPO_SECRET2: ${{ secrets.REPO_SECRET2 }}    
          with:
            repository: ${{ github.repository }}
            secrets-prefix: 'SECRETS_'
            secrets-type: 'repo'
    export-secrets-env:
      name: Export Secrets (env)
      runs-on: windows-latest
      environment: 'production'
      steps:
        - name: Export Secrets to CSV (env)
          uses: martins-vds/export-secrets-action@v1.2    
          env:
            SECRETS_ENVIRONMENT_SECRET1: ${{ secrets.ENVIRONMENT_SECRET1 }}
            SECRETS_ENVIRONMENT_SECRET2: ${{ secrets.ENVIRONMENT_SECRET2 }}
          with:
            repository: ${{ github.repository }}
            secrets-prefix: 'SECRETS_'
            secrets-type: 'env'
            environment-name: 'production'