name: Export Secrets to Artifact

on:
  workflow_dispatch:

env:
  PREFIX_SECRETS: 'SECRETS_'

jobs:
    export-secrets:
        name: Export Secrets
        runs-on: windows-latest  
        steps:
          - name: Export Secrets to CSV (repo)
            uses: martins-vds/export-secrets-action@v1.1
            env:
                '${{ env.PREFIX_SECRETS }}REPO_SECRET1': ${{ secrets.REPO_SECRET1 }}
                '${{ env.PREFIX_SECRETS }}REPO_SECRET2': ${{ secrets.REPO_SECRET2 }}    
            with:
                repository: ${{ github.repository }}
                secrets-prefix: ${{ env.PREFIX_SECRETS }}
                secrets-type: 'repo'